### ISSUE TITLE
Libby fails to download

### ISSUE THREAD

**Issue by rainrdx** [cbguder/books#13]
Hi,

Thank you for supporting this project. It seems that all of a sudden, any libby download is giving me the following error message:

unsupported protocol scheme ""

**Comment by cbguder** [comment]
Thanks for reporting! Should be fixed in [v0.3.4](https://github.com/cbguder/books/releases/tag/v0.3.4).

**Comment by rainrdx** [comment]
Thank you for maintaining this!
